name: interview_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  
  flutter:
    sdk: flutter

  flutter_bloc: ^7.0.0
  flutter_localizations: 
    sdk: flutter        
  intl: ^0.17.0
  http: ^0.13.4
  equatable: ^2.0.3
  string_validator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/config/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf
        
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
